[package]
name = "tui-menu"
version = "0.1.0"
edition = "2021"
description = "A menu widget for tui-rs"
license = "MIT OR Apache-2.0"
keywords = ["tui"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.19"

[dev-dependencies]
crossterm = "0.25"
